/**
 * Notification Types and Enums
 */
const NOTIFICATION_TYPES = {
  COMPLAINT_STATUS_UPDATE: 'COMPLAINT_STATUS_UPDATE',
  PICKUP_APPROVAL: 'PICKUP_APPROVAL',
  PICKUP_ASSIGNMENT: 'PICKUP_ASSIGNMENT',
  PICKUP_COMPLETION: 'PICKUP_COMPLETION',
  SERVICE_BROADCAST: 'SERVICE_BROADCAST'
};

const NOTIFICATION_PRIORITY = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

const NOTIFICATION_CHANNELS = {
  AWS_SNS_CLOUD: 'AWS_SNS_CLOUD',
  LOCAL_NOTIFICATION_BUS: 'LOCAL_NOTIFICATION_BUS'
};

module.exports = {
  NOTIFICATION_TYPES,
  NOTIFICATION_PRIORITY,
  NOTIFICATION_CHANNELS
};
